### ISSUE TITLE
How can I force to use a choice???

### ISSUE THREAD

**Issue by durancu** [iliyaZelenko/vue-cool-select#1]
I want to force the user to make a choice from the list. It's that possible?

**Comment by iliyaZelenko** [comment]
Thank you for using my library, I am very pleased. Sorry I could not answer yesterday. How I understand you need to show an error if the user did not make a choice? I made an [example](https://codesandbox.io/s/yk6k2v6w59) of how this can be done on the current version.  If you can offer something to improve the API, I will definitely try to do it.

**Comment by iliyaZelenko** [comment]
I have released a new version. Now you can make a field with an error. See [this example](https://codesandbox.io/s/nkx09nqqj0).

![](https://i.imgur.com/97qEqwi.png)

I am ready to correct any shortcomings.
