### ISSUE TITLE
Initial value for the component

### ISSUE THREAD

**Issue by andriasmelianus** [iliyaZelenko/vue-cool-select#104]
Hi, it's me again.
So I create separated component to simplify the input of a field in a table, and include that component to my form. And add `v-model` support to that component.
But sometime we need to edit a row using the same form. As usual, an edit form will contain the initial value from a database. But I found that I am unable to set an initial value for this component.
Here is the code I use:

[CodeSanbox](https://codesandbox.io/s/y2km0xjllz)

Can we have a solution for this problem?
CMIIW
Thanks

**Comment by andriasmelianus** [comment]
After further reading the documentation, `searchText` is what I need.
Since this component use an `input` element, it is possible that the user give a new value and add that value to the database/select options.
Thanks anyway! :handshake:

**Comment by iliyaZelenko** [comment]
Hi. Glad you found a solution. I would answer you earlier, but I was a little busy. 
If there are any other questions or suggestions, I’m just glad to hear it. 
Good luck with your project!

**Comment by andriasmelianus** [comment]
Hi, it's okay bro. I just need to read more carefully the documentation.
Thanks for this really cool component! :handshake:
