### ISSUE TITLE
Searching and then using arrow keys resets items

### ISSUE THREAD

**Issue by Revenio** [iliyaZelenko/vue-cool-select#13]
When searching and it shows more than one item but not all items, it resets items to initial list when using arrow keys.
Cant not be replicated in 1.5.5.

**Comment by iliyaZelenko** [comment]
Hello, thanks for the message. This is the expected behavior by default, when you move with the arrows, it resets the search and instantly selects an item. You can use `arrows-disable-instant-selection` prop to disable the instant selection. See https://codesandbox.io/s/50wvzo155p
