### ISSUE TITLE
Give ID to Input Element

### ISSUE THREAD

**Issue by andriasmelianus** [iliyaZelenko/vue-cool-select#130]
Hi, it's me again!
So I want to change my cursor focus to another input with <kbd>Enter</kbd> key to speed up data input process.
Unfortunately, we cannot use `el.nextElementSibling` or `el.nextSibling` in BootstrapVue, since the input element placed within the `<b-form-group>`.
I think I can use ID to identify every input element within a form and jump from one to another input easily.
So, can you add one more `props`, say `inputId`, and pass it value to the ID attribute to the `<input />` element?
Or maybe you have a better solution for this problem, let me know.
Thanks

**Comment by iliyaZelenko** [comment]
Hey. I think you can use `inputElCustomAttributes` prop. 

Perhaps you can give an id like this: 

```vue
<cool-select
  id="my-id"
/>
```
I think the focus will work when the focus is on this identifier (`my-id`).

**Comment by andriasmelianus** [comment]
Hi,
`inputElCustomAttributes` is the solution here. Thank you!
Sorry for the trouble :grimacing:
