### ISSUE TITLE
Spellcheck attribute support

### ISSUE THREAD

**Issue by samkuhn** [iliyaZelenko/vue-cool-select#144]
Our list has many technical words that produce red spellchecker underlines on the text input. Would it be possible to add an option that puts spellcheck="false" onto the input element? As we have no way of disabling this from our side right now.

**Comment by iliyaZelenko** [comment]
I think this way will help you:
```vue
<cool-select
  :input-el-custom-attributes="{ spellcheck: 'false' }"
/>
```

**Comment by samkuhn** [comment]
Ah yes.. just found that. Sorry to bother you and thanks!
