### ISSUE TITLE
how to customize css?

### ISSUE THREAD

**Issue by frpacheco** [iliyaZelenko/vue-cool-select#149]
This is an excellent component. Thank you for making it available.
How do I customize component css?
Is this possible?

**Comment by iliyaZelenko** [comment]
> This is an excellent component. Thank you for making it available.

I am very pleased, thank you.

> How do I customize component css?
> Is this possible?

You can try these variants:

1. https://github.com/iliyaZelenko/vue-cool-select/issues/2#issuecomment-473674157
2. https://github.com/iliyaZelenko/vue-cool-select/pull/90#issuecomment-473728474

Hope this helps.
