### ISSUE TITLE
Is there a way to disable cool-select on mobile?

### ISSUE THREAD

**Issue by kris10cabrera** [iliyaZelenko/vue-cool-select#151]
This is a great component, thanks. 
Is there a way to disable the cool-select on mobile? So that a dropdown reverts to default mobile behavior, rather than the cool-select component.

**Comment by iliyaZelenko** [comment]
> This is a great component, thanks.

Thank you, I saw you once gave a star, very nice.

I think this is beyond the scope of this component, it needs to be done manually in your project. I would suggest to make a universal component `BaseSelect` (you can call it as stated in the [best practices](https://vuejs.org/v2/style-guide/#Base-component-names-strongly-recommended)), which would work as `cool-select` everywhere except for mobile devices.

You can use **transparent wrapper**r pattern, this is a very popular pattern in Vue.

I have prepared a [DEMO](https://codesandbox.io/s/vue-template-12y8j) for you. I showed the idea how to do it.

I hope I helped you, write if you have any more questions.

**Comment by kris10cabrera** [comment]
Thank you!
