### ISSUE TITLE
Disable options

### ISSUE THREAD

**Issue by 1stKarkan** [iliyaZelenko/vue-cool-select#161]
Hello,
Is it possible to make options disabled, so the user can't click them? Like the "disabled" attribute for options in a html select.
We'd like to show the availability of tickets in the cool-select. Sold out options should not be selectable but still be visible. Right now we added a css class to the option text to show it in a different color, but it would be really nice if we could disable these options entirely to prevent the user from selecting them.

Great component btw :)

**Comment by iliyaZelenko** [comment]
Hi, I am very glad that you use my component! 😄

There is no built-in feature in this component. But I made a [simple example](https://codesandbox.io/s/4zlkjr9xow?fontsize=14&initialpath=%2Fdisabled-items) for you how to do it easily.
I think it is not very difficult to use. In the future I will do a more convenient way, thanks for the idea.

**Comment by 1stKarkan** [comment]
Thank you very much!
