### ISSUE TITLE
Is there a way to make the dropdown menu already open?

### ISSUE THREAD

**Issue by JPabloPS** [iliyaZelenko/vue-cool-select#169]
I have a question. I need it so when the user enters the page the dropdown menu is open. 
I haven't found any props for this. I don't know if I need to make a focus manually. Can this be done?

**Comment by iliyaZelenko** [comment]
Hi, thanks you for using my component, very glad.

There is no prop, but I created an [example](https://codesandbox.io/s/4zlkjr9xow) for you. It's pretty simple done.

Hope this helps you.
