### ISSUE TITLE
Vue Select styling

### ISSUE THREAD

**Issue by acentfrio** [iliyaZelenko/vue-cool-select#188]
Good day,

I'd like to know how a styling on this amazing component works.
I'd like to remove border and border-color and border-shadow from the select box

Thanks for quick reply

**Comment by iliyaZelenko** [comment]
Hi, thanks for using my component!

You could see [what styles are being used](https://github.com/iliyaZelenko/vue-cool-select/blob/master/src/styles/themes/bootstrap.styl) and redefined, although this is a fairly obvious answer, you probably have a more complicated situation.

Perhaps in the next week or two I will release a new version where you can fully use your styles. This is the most flexible option.

Maybe `inputStyles` prop will also help you.

**Comment by acentfrio** [comment]
Can u make an example of how can styles be redefined

Thanks for quick reply

**Comment by iliyaZelenko** [comment]
Sorry I couldn’t answer right away. Here is an example of what you requested:

```vue
<style>
.IZ-select__input.IZ-select__input--focused {
  border-color: transparent;
  box-shadow: none;
}
</style>
```

Also [here](https://github.com/iliyaZelenko/vue-cool-select/issues/149) is a similar topic.

**Comment by iliyaZelenko** [comment]
@acentfrio Have you got it? Question can be considered closed?

**Comment by acentfrio** [comment]
The issue is closed. thank you

**Comment by iliyaZelenko** [comment]
@acentfrio this is good. I also want to draw your attention to the fact that with the new version `3.x`, theme styles now [need to be imported manually](https://github.com/iliyaZelenko/vue-cool-select#get-started), this gives you the flexibility that you can fully import your own theme of styles.
