### ISSUE TITLE
HTML 5 required input

### ISSUE THREAD

**Issue by jwells967** [iliyaZelenko/vue-cool-select#190]
would it be possible to include an option to use built in html 5 input required property to control validation rather than using the combination of successful and error-message

**Comment by iliyaZelenko** [comment]
@jwells967 can you try the `input-el-custom-attributes` prop?
```vue
:input-el-custom-attributes="{ required: true }"
```
I think this will put `required` attribute for `<input>`.

**Comment by jwells967** [comment]
Thank you, thank you! This is exactly what i needed!

The quick reply is greatly appreciated
