### ISSUE TITLE
Pressing enter key to select item submits form

### ISSUE THREAD

**Issue by eberkund** [iliyaZelenko/vue-cool-select#196]
When I press the enter key to select an item the form gets submitted, this differs from the behaviour of the built in browser select. Is there a way to change this behaviour? Maybe block this event from getting through somehow.

Thanks, great component!

**Comment by iliyaZelenko** [comment]
@eberkund Thanks for using the component.
Your problem can be solved as follows.

You can solve the problem using `@keydown.enter.native.prevent` (huge chain!):

```vue
<form>
  <cool-select
    v-model="selected"
    :items="items"
    placeholder="Select name"
    @keydown.enter.native.prevent
  />
</form>
```

I checked it works.

In my component, I think I need to save the `submit` event, but so that it only works when the menu is closed.
