### ISSUE TITLE
Typescript - missing some types in vue-cool-select/types/types.d.ts

### ISSUE THREAD

**Issue by pplusawork** [iliyaZelenko/vue-cool-select#218]
Low priority - it throws errors messages in the compiler but everything still works fine.
Version 3.0.2

Specific messages are:
Parameters implicitly have 'any' type:
Line 9, 10, 11, 41 through 48
Functions lack return-type annotation, implicitly have 'any' return type:
Line 41 through 48

**Comment by iliyaZelenko** [comment]
The reason is that you have `"noImplicitAny": true` enabled, `any` is used in my types, so the compiler complains.
You can use `"skipLibCheck": true,` as described in [this](https://stackoverflow.com/a/40838654/5286034) answer.
Hope this helps.

**Comment by pplusawork** [comment]
Got it - thanks!
Great work too
