### ISSUE TITLE
no-data generates [Vue warn]: Error in render: "TypeError: Cannot read property 'options' of undefined"

### ISSUE THREAD

**Issue by mikekelly1** [iliyaZelenko/vue-cool-select#223]
I am getting the above vue warning as soon as I type in a set of characters that produce no data from my data set. I assume this is something to do with my local dev installation as the demo works perfectly. I assume that the problem is that $coolSelect is not available, i.e. from component.vue

`<slot name="no-data">
        {{ $coolSelect.options.text.noData }}
 </slot>`

and $coolSelect is imported from main.js

For some reason I get a console warning rather than the 'No data available' message. No error is thrown so the application continues OK. 

I tried installing with yarn and npm but it made no difference. Do you have any idea what I have done wrong?

**Comment by iliyaZelenko** [comment]
Hi, thanks for using the component and detailed information on the problem.

Maybe a silly question, but are you using the code below? (before using the component itself)

```js
import { CoolSelectPlugin } from 'vue-cool-select'

// paste the line below only if you need "bootstrap" theme
import 'vue-cool-select/dist/themes/bootstrap.css'
// paste the line below only if you need "material-design" theme
import 'vue-cool-select/dist/themes/material-design.css'
// you can also import your theme

Vue.use(CoolSelectPlugin)
```

**Comment by mikekelly1** [comment]
Thanks for responding so quickly. Not a silly question at all. I was
importing

import { CoolSelect } from 'vue-cool-select'

and using

Vue.use(CoolSelect)


This all worked beautifully apart from the no-data issue.

I changed it to CoolSelectPlugin and the problem is fixed. Thank you very much.

Thank you too for the component. I love it.

Rgds

Mike

**Comment by iliyaZelenko** [comment]
I am very glad that I immediately found a solution. Your code did not work before due to the fact that you imported the component itself, not a plugin (you can see [this line](https://github.com/iliyaZelenko/vue-cool-select/blob/master/src/main.js#L2) of code).

I’m glad to help if you have any more questions now or in future.

**Comment by mikekelly1** [comment]
I see now. Thanks again.
