### ISSUE TITLE
Blurring the component after onSelect

### ISSUE THREAD

**Issue by pasictarik** [iliyaZelenko/vue-cool-select#225]
Loving the component so far, and using it on my current project. However, there is a feature that I would like you to add and that seems fit for this component. It would be great to have a prop to invoke blur after selecting an item, or to be able to emit blur inside the select event.

I tried doing this by emitting blur inside the select event handler as in
`  onSelect (item) {
    console.log('select', this.$refs.coolselect)
    this.$refs.coolselect.$emit('blur');
  }`

also tried
`  onSelect (item) {
    this.$refs.coolselect.wishShowMenu = false;
    this.$refs.coolselect.focused = false;
  }`

however niether work, also tried setting a timeout, that doesn't work either. If you have another option that I could try, please let me know. I did not try emitting blur outside the onSelect listener but I believe that I should be allowed to blur it inside.

the component is awesome I hope that you'll add this feature soon

**Comment by iliyaZelenko** [comment]
Hi, thanks for using the component. I’ll help you with joy. I think the following code will help you: 

```vue
<cool-select
  ref="select"
  v-model="selected"
  :items="items"
  @select="onSelect"
/>
```

and method `onSelect`:

```js
onSelect () {
  this.$refs.select.setBlured()
}
```

**Comment by pasictarik** [comment]
wow I feel awful hahahah, I tried that too initially but instead of writing "setBlured()" I used "setBlurred()", and kept getting 'setBlurred()' is not a function 🤣. Isn't blurred grammatically correct?

Thanks a lot, it works perfectly now !

**Comment by iliyaZelenko** [comment]
Wow, haha, excuse me for such a name for the function. The fact is that I do not have a high level in English and I can make such mistakes. This is an interesting situation, each of us has gained experience.
