### ISSUE TITLE
Dropup position when falling out of container or page

### ISSUE THREAD

**Issue by Blastius** [iliyaZelenko/vue-cool-select#228]
When I have a select on the bottom of my page, the dropdown menu increases the page height instead of displaying it above the input. See the gif below for a quick example:

![vue-cool-select-bottom-of-page-dropdown](https://user-images.githubusercontent.com/10246822/66823144-eaa56300-ef45-11e9-85fa-a95a196b15cd.gif)

Is there a simple solution for this to apply myself, or does it require editing the package?

Thanks for this amazing package, there is currently no better one!

**Comment by iliyaZelenko** [comment]
I reviewed your problem two hours ago. Now I’m thinking how best to solve it. If there is a simple solution, it only makes the menu appear at the top instead of the bottom, but does not dynamically position it.

I also noticed that the menu is not exactly positioned horizontally. It was like that from the very beginning, didn't you break it? As far as I see you have google chrome, like me, everything should work there.

**Comment by Blastius** [comment]
As you can see, this is in your codesandbox environment. The only thing I changed was decrease the height of `.app-body-wrap` from `100vh` to `400px`.

For the dropup, I discovered that it is possible to set it on top of the input by setting the `.IZ-select__menu` class to `top: initial !important` and `bottom: 100%;`. The next challenge is when to apply this, we need something like popper.js applies to their popovers and tooltips I guess to check when the given element(dropdown) is out of boundaries?

**Comment by iliyaZelenko** [comment]
I also thought about popper.js at the beginning, but I would like my project to be without dependencies, so I will think about my option. Thanks for the styles that come in handy. 

The task is interesting, I will try to solve it in the near future. I hope this is not very urgent for you?

**Comment by Blastius** [comment]
Thank you for giving this issue attention, I'll set a prop for now with the given custom styles. I will follow your updates and hope you will have a better solution soon!

**Comment by Blastius** [comment]
This article might help us for a solution @iliyaZelenko: https://gomakethings.com/how-to-check-if-any-part-of-an-element-is-out-of-the-viewport-with-vanilla-js/

**Comment by iliyaZelenko** [comment]
@Blastius I’ll do it right now. Thank you very much for the link, it seems quite easy to do.

**Comment by iliyaZelenko** [comment]
Implemented in #236, spent 5 hours on it, I had to write [a lot of code](https://github.com/iliyaZelenko/vue-cool-select/pull/236/files), I did not expect this at the beginning. Now in the new version there are 2 new props:

1) `menu-dynamic-position` (`true` by default) — sets the dynamic position behavior for the menu (based on viewport).
2) `menu-default-position` (`bottom` by default) — sets menu's default position.

Please confirm if everything is working fine.

**Comment by Blastius** [comment]
Looking good so far, thank you very much for adding this feature so quick!
