### ISSUE TITLE
position prop

### ISSUE THREAD

**Issue by VeronQ** [iliyaZelenko/vue-cool-select#234]
Would you consider adding a new **position** prop to change the select position depending on the current scroll position?

Maybe something like this:
```vue
position: [ 'auto', 'above', 'below' ]
```

Thank your for this plugin.

**Comment by iliyaZelenko** [comment]
@VeronQ Thanks for using my plugin. It seems like 2 days ago I was asked to do [something similar](https://github.com/iliyaZelenko/vue-cool-select/issues/228). Apparently this is what you need, but in your version there is still the opportunity to specify the static position `above` or `below`.

**Comment by iliyaZelenko** [comment]
Please, see [this answer](https://github.com/iliyaZelenko/vue-cool-select/issues/228#issuecomment-543283071).

**Comment by VeronQ** [comment]
It works like a charm !
Thank you for adding this new feature.
