### ISSUE TITLE
vue-cool-select scrolls the page automatically when clicking on the searchbar

### ISSUE THREAD

**Issue by signmeuptwice** [iliyaZelenko/vue-cool-select#273]
Using vue-cool-select in different components
Whenever I click on the component it scrolls the page to put the component at the top.

using
"vue": "^2.5.22",
"vue-cool-select": "^1.6.2",

example of a problematic instance
```
 <cool-select
        v-model="userSelected"
        :items="userResults"
        :loading="searching"
         item-text="label"
         placeholder="Choose user"
        disable-filtering-by-search
         @search="onSearch">

         <template slot="no-data">{{noData ? "No Result." : "Two characters minimum." }}</template>
              <template slot="item" slot-scope="{item}">
                    <div>{{item.label}} - {{item.email}}</div>
         </template>
 </cool-select>
```

**Comment by iliyaZelenko** [comment]
Try `:allow-mobile-scroll="false"` prop.

**Comment by signmeuptwice** [comment]
@iliyaZelenko no effect

**Comment by signmeuptwice** [comment]
found the bug:
WITH or WITHOUT :allow-mobile-scroll="false" I get the same behaviuor:

If my screen is small and I reload the page it scrolls to the top
If my screen is large and I reload the page no problem; then I can resize the screen to small without issues

So the problem only happens when the page is reloaded below the width treshold

**Comment by iliyaZelenko** [comment]
[That's](https://github.com/iliyaZelenko/vue-cool-select/blob/6406b36fd4e8486aaf55304e4f01bf317fa25ab2/src/component.vue#L370) where my code checks before scrolling.

Maybe you have a typo or syntax (make sure you don’t forget about `:`), try to throw off the full code. Also try `:allowMobileScroll="false"`

**Comment by signmeuptwice** [comment]
:allowMobileScroll="false" solved the issue
