### ISSUE TITLE
Get list from JSON Array

### ISSUE THREAD

**Issue by Quentin90** [iliyaZelenko/vue-cool-select#3]
Hello and thanks for the cool select,

but i was wondering if is there a way to give the select a json array like this : 
_`[{"first_name":"lati"},{"first_name":"wassel"} ... ]`_

Or do i have to parse it (JSON.parse) before ?

**Comment by iliyaZelenko** [comment]
Hello, thanks for using my component, I am very pleased. 

It looks like a good idea, thanks, I will definitely implement it in the next version. 

Also, the following props can also help you:

- `item-text` — property in item for text
- `item-value` — property in item for value

You can use like this (after JSON.parse):

```vue
<cool-select 
  v-model="selected" 
  :items="items"
  item-text="first_name"
  item-value="first_name"
/>
```

I hope I helped you, good luck!

**Comment by Quentin90** [comment]
I will give it a try thanks ! 
And good luck for the JSON implement, it will help a lot of people who create APIs

**Comment by iliyaZelenko** [comment]
Hello, I added your wish in the [new version](https://github.com/iliyaZelenko/vue-cool-select/releases/tag/v1.4.0).

Now people will really be more comfortable! 👍
