### ISSUE TITLE
Retain the text entered if we click outside the search box

### ISSUE THREAD

**Issue by neerajvv** [iliyaZelenko/vue-cool-select#302]
Hi,

Im using the version : "vue-cool-select": "^3.5.1"

How to make the search box act like a normal text field, even if we didn't select any search list option.

Currently when you click outside the search box the text entered in the field is getting reset.

**Comment by iliyaZelenko** [comment]
Hi, you can use `resetSearchOnBlur` prop from [docs](https://iliyazelenko.github.io/vue-cool-select/#/docs).

**Comment by neerajvv** [comment]
Thank You.. Got it.
