### ISSUE TITLE
Is this lib compatible with vue3?

### ISSUE THREAD

**Issue by andy3520** [iliyaZelenko/vue-cool-select#381]

**Comment by wouter-muller** [comment]
I also would like to know about this :)

**Comment by wouter-muller** [comment]
I just took 1 minute to install it, and concluded it is NOT compatible with Vue 3.

When running `npm install --save vue-cool-select` i get an error saying that Vue ^2.5.17 is a dependency...

**Comment by wouter-muller** [comment]
Closed as in "we are not going to support Vue 3"? Or is it perhaps a duplicate?
