### ISSUE TITLE
Scroll to selected item through arrows

### ISSUE THREAD

**Issue by mariosh346** [iliyaZelenko/vue-cool-select#39]
On REST API example if you add arrows-disable-instant-selection you can see that the selected item was not followed if you navigate with arrows

**Comment by iliyaZelenko** [comment]
Maybe I did not understand something, but everything seems to work as expected. Text turns blue if an item is selected through pointers.

I tried with and without `arrows-disable-instant-selection`, text selection is the same, the only thing that without this prop selection goes instantly.

The screenshot shows that the second element is selected through the arrows, its title is blue:


![image](https://user-images.githubusercontent.com/13103045/53654909-928c4b80-3c57-11e9-9495-8c237d9f81ab.png)

Is your browser showing not the same? 

You gave me an idea: in item _scoped slot_, I can add a property transfer, if the current item is selected via arrows, users will be able to change the content depending on that. I can also pass the mouse over state.

**Comment by mariosh346** [comment]
When you navigate after the visible items it does not show the hidden

[image: image.png]

Στις Παρ, 1 Μαρ 2019 στις 7:28 μ.μ., ο/η Илья <notifications@github.com>
έγραψε:

**Comment by iliyaZelenko** [comment]
I think I understand, do you want the menu to scroll by following the selected item? That is, in this way the selected element will always be visible, no need to scroll with the mouse. Are you talking about it?

**Comment by mariosh346** [comment]
Yes this is it what I meant!

Στις Παρ, 1 Μαρ 2019 στις 9:05 μ.μ., ο/η Илья <notifications@github.com>
έγραψε:
