### ISSUE TITLE
Errors in v.1.5.1 with Chrome and Firefox

### ISSUE THREAD

**Issue by ole1105** [iliyaZelenko/vue-cool-select#4]
Hi again, recently I updated your vue-cool-select to v. 1.5.1 and I found a cople errors.

Both errors happen when I use the `disable-search` prop.

In Firefox when I put two or three vue-cool-select, the second one displays drop-down options without close drop-down options at first select, see the next image.
![imagen](https://user-images.githubusercontent.com/33353160/50111373-07341a00-0213-11e9-93cc-c322c6b39eee.png).

In Chrome doesn't select any option, only show options and close drop-down when release clic button.

If you need more details just ask for it. Thank you a lot for your component, best regards.

**Comment by iliyaZelenko** [comment]
Hi, I guess I should have called the package vue-not-cool-select-with-alot-of-errors )) 

Sorry for the inconvenience, it is not so easy to calculate all the scenarios, especially when the behavior of browsers is different.

I fixed the error in chrome. In firefox, I tried to repeat your problem (after I fixed it in chrome) and it looks like the error has passed.

**Comment by ole1105** [comment]
It's not your fault, it's Murphy's fault. "what-we-programmers-keep-silent".

Now it's fixed in both browsers, glad to help reporting errors, at least. Thank you a lot.
