### ISSUE TITLE
Uncaught TypeError: Cannot read property 'contains' of undefined

### ISSUE THREAD

**Issue by cvaize** [iliyaZelenko/vue-cool-select#6]
A strange error appears. Everything works, but the error still appears.
![image](https://user-images.githubusercontent.com/26907947/50477928-5b4bb500-09f0-11e9-90c8-f5904573b3f0.png)

**Comment by cvaize** [comment]
I will make a clarification. Error occurs when a component is destroyed

**Comment by iliyaZelenko** [comment]
Thanks for the info and for using the component. Will be fixed soon.

**Comment by iliyaZelenko** [comment]
The error is fixed in version 1.5.4. Thanks again for the information about it! Happy holidays!
