### ISSUE TITLE
does not fire @select when using keyboard

### ISSUE THREAD

**Issue by danieldocki** [iliyaZelenko/vue-cool-select#9]
when you search for an item and use the down arrow and then enter it does not fire @select.

example: https://codesandbox.io/s/zwn46x1kpx

maybe it's the problem here
https://github.com/iliyaZelenko/vue-cool-select/blob/master/src/component.vue#L66

**Comment by iliyaZelenko** [comment]
Fixed in `1.6.0`. Note that the item is selected when you jump to it with arrows, pressing the enter button will simply close the select.

Demo: https://codesandbox.io/s/w6m23jv3o5

**Comment by danieldocki** [comment]
Do not be ashamed ... I really enjoyed your lib. Thanks for the correction.

**Comment by danieldocki** [comment]
is it better to put the item as selected when the enter is fired and not keydown or keyup?

**Comment by iliyaZelenko** [comment]
Perhaps this is better, I do not see a serious reason to rewrite the code. 
For example, in html `<select>` works on the same logic as this component.
